# Generated by Django 3.0.4 on 2020-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='название основного раздела', max_length=100, null=True, verbose_name='Название раздела')),
                ('slug', models.SlugField(blank=True, help_text='название url адреса', null=True, unique=True, verbose_name='URL адрес')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Основное меню',
            },
        ),
    ]
