# Generated by Django 3.0.4 on 2020-03-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_subbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbar',
            name='subname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbar', to='data.Mainbar'),
        ),
    ]
