# Generated by Django 3.0.4 on 2020-03-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_subbar_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbar',
            name='mobile',
            field=models.BooleanField(default=True, help_text='поставить галочку если нужно в мобильной версии', verbose_name='Мобильная версия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subbar',
            name='mobile',
            field=models.BooleanField(default=True, help_text='поставить галочку если нужно в мобильной версии', verbose_name='Мобильная версия'),
            preserve_default=False,
        ),
    ]
