# Generated by Django 3.0.4 on 2020-04-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
    ]
