# Generated by Django 3.0.4 on 2020-04-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200404_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thirdcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdproducts', to='data.Category'),
        ),
        migrations.CreateModel(
            name='SecondCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('secondcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondproducts', to='data.Category')),
            ],
            options={
                'verbose_name': 'Вторая Категория',
                'verbose_name_plural': 'Вторая Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FirstCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('firstcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstproducts', to='data.Category')),
            ],
            options={
                'verbose_name': 'Первая Категория',
                'verbose_name_plural': 'Первая Категории',
                'ordering': ('name',),
            },
        ),
    ]
