# Generated by Django 3.0.4 on 2020-04-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200404_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thirdcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdproducts', to='data.SecondCategory'),
        ),
        migrations.AlterField(
            model_name='secondcategory',
            name='secondcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondproducts', to='data.FirstCategory'),
        ),
    ]
