# Generated by Django 3.0.4 on 2020-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200404_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Фильтры',
                'verbose_name_plural': 'Фильтры',
                'ordering': ('name',),
            },
        ),
    ]
