# Generated by Django 3.0.4 on 2020-04-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_sorter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorter',
            name='sorter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorter', to='data.Category'),
        ),
    ]
