# Generated by Django 3.0.4 on 2020-05-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Работы',
                'verbose_name_plural': 'Работы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('jobs', models.ManyToManyField(related_name='process', to='calculator.Job')),
            ],
            options={
                'verbose_name': 'Элементы',
                'verbose_name_plural': 'Элементы',
                'ordering': ('name',),
            },
        ),
    ]
