# Generated by Django 3.0.4 on 2020-05-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_sorter_sorter'),
        ('calculator', '0002_job_norms'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='materials', to='data.Product'),
        ),
    ]
