# Generated by Django 3.0.4 on 2020-05-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_type_typewall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='type',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='typewall',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='typewall',
            name='slug',
        ),
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.ManyToManyField(related_name='typematerial', to='calculator.Job'),
        ),
        migrations.AddField(
            model_name='element',
            name='typewall',
            field=models.ManyToManyField(related_name='typeelement', to='calculator.Job'),
        ),
        migrations.AddField(
            model_name='norms',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_norms', to='calculator.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, help_text='название типа', max_length=100, null=True, verbose_name='Название типа'),
        ),
        migrations.AlterField(
            model_name='typewall',
            name='name',
            field=models.CharField(blank=True, help_text='название типа', max_length=100, null=True, verbose_name='Название типа'),
        ),
    ]
