# Generated by Django 3.0.4 on 2020-05-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20200513_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='typewall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_norms', to='calculator.TypeWall'),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.ManyToManyField(related_name='typematerial', to='calculator.Type'),
        ),
        migrations.AlterField(
            model_name='element',
            name='typewall',
            field=models.ManyToManyField(related_name='typeelement', to='calculator.TypeWall'),
        ),
    ]
